
from django.contrib import admin
from django.urls import path, include
from rest_framework.documentation import include_docs_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('watch/', include('watchlist_app.api.urls')),
    path('account/', include('user_app.api.urls')),
    
    # path('api-auth', include('rest_framework.urls')),
]


urlpatterns.extend([
    # For autogenerated API documentation
    path(
        "api/docs/",
        include_docs_urls(title="Watchmate API Docs"),
        name='drf-doc'
    ),
])